added check for zlib

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15193,6 +15193,53 @@ fi
 
 
 
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for gzungetc in -lz" >&5
+$as_echo_n "checking for gzungetc in -lz... " >&6; }
+if ${ac_cv_lib_z_gzungetc+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lz  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char gzungetc ();
+int
+main ()
+{
+return gzungetc ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_link "$LINENO"; then :
+  ac_cv_lib_z_gzungetc=yes
+else
+  ac_cv_lib_z_gzungetc=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_z_gzungetc" >&5
+$as_echo "$ac_cv_lib_z_gzungetc" >&6; }
+if test "x$ac_cv_lib_z_gzungetc" = xyes; then :
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBZ 1
+_ACEOF
+
+  LIBS="-lz $LIBS"
+
+else
+  echo "zlib run time library not found";exit 1
+fi
+
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
